### ISSUE TITLE
Failure to deploy

### ISSUE THREAD

**Issue by MrVisioo** [Uniswap/routing-api#305]
I successfully deployed and used routing api. I then undeployed it running `cdk destroy RoutingAPIStack`.  Now when I try to deploy it again a get an error at some point during deployment process. I'm not sure how to diagnose this. I tried to revert back to the older version of routing api I used previously. I tried to delete s3 buckets that were left after the process and repeated bootstrapping process hoping to arrive at a known state. Now my only assumption would be that the problem is that I use AWS CDK v2, which documentation says should be compatible anyways. 

I want a confirmation if the problem is on my end  or not and to take a hint as to what is the source of the problem and how to fix it. 

```
    at FullCloudFormationDeployment.monitorDeployment (/usr/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/lib/node_modules/aws-cdk/lib/index.js:429:153380)
    at async /usr/lib/node_modules/aws-cdk/lib/index.js:429:137002

The stack named RoutingAPIStack failed creation, it may need to be manually deleted from the AWS console: 
ROLLBACK_COMPLETE: Embedded stack arn:aws:cloudformation:region:id:stack/RoutingAPIStack-RoutingDatabaseStackNestedStackRoutingDatabaseStackNestedStackResource-9FQTG2UOR6G0/8afadc00-400e-11ee-83a6-0a8c8e93396c was not successfully created: 
The following resource(s) failed to create: [CacheReqFlagDB8C36522C, RouteCachingDB1361CA88, V3PoolsCachingDB667282EE]. 
```

**Comment by MrVisioo** [comment]
Had to delete tables in DynamoDB, then deploy worker.
