### ISSUE TITLE
indexing_error while fetching pools on subgraph

### ISSUE THREAD

**Issue by onehumanbeing** [Uniswap/routing-api#470]
I had this issues while while fetching pools on the subgraph
```
{
    "name": "RoutingLambda",
    "requestId": "73a213f3-bd36-da34-83c6-db19e46c028b",
    "hostname": "169.254.81.245",
    "pid": 12,
    "level": 30,
    "err": {
        "message": "indexing_error: {\"response\":{\"errors\":[{\"message\":\"indexing_error\"}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n      query getPools($pageSize: Int!, $id: String) {\\n        pools(\\n          first: $pageSize\\n          \\n          where: { id_gt: $id }\\n        ) {\\n          id\\n          token0 {\\n            symbol\\n            id\\n          }\\n          token1 {\\n            symbol\\n            id\\n          }\\n          feeTier\\n          liquidity\\n          totalValueLockedUSD\\n          totalValueLockedETH\\n        }\\n      }\\n    \",\"variables\":{\"pageSize\":1000,\"id\":\"\"}}}",
        "name": "Error",
        "stack": "Error: indexing_error: {\"response\":{\"errors\":[{\"message\":\"indexing_error\"}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n      query getPools($pageSize: Int!, $id: String) {\\n        pools(\\n          first: $pageSize\\n          \\n          where: { id_gt: $id }\\n        ) {\\n          id\\n          token0 {\\n            symbol\\n            id\\n          }\\n          token1 {\\n            symbol\\n            id\\n          }\\n          feeTier\\n          liquidity\\n          totalValueLockedUSD\\n          totalValueLockedETH\\n        }\\n      }\\n    \",\"variables\":{\"pageSize\":1000,\"id\":\"\"}}}\n    at /var/task/index.js:80:13966\n    at l (/var/task/index.js:80:9141)\n    at Object.next (/var/task/index.js:80:8445)\n    at p (/var/task/index.js:80:8003)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    "msg": "Failed to get pools from subgraph. Retry attempt: 1",
    "time": "2024-02-16T06:47:49.956Z",
    "v": 0
}
```
As a result poolCache.json for chains like polygon aren't created, so the routing-api can't work.

I use the main branch with the .env like this (didn't change the code)
```
TENDERLY_USER=xxx
TENDERLY_PROJECT=xxx
TENDERLY_ACCESS_KEY=xxx
THROTTLE_PER_FIVE_MINS=''
JSON_RPC_PROVIDER_1=https://mainnet.infura.io/v3/xxx
JSON_RPC_PROVIDER_3=https://ropsten.infura.io/v3/xxx
JSON_RPC_PROVIDER_4=https://rinkeby.infura.io/v3/xxx
JSON_RPC_PROVIDER_5=https://goerli.infura.io/v3/xxx
JSON_RPC_PROVIDER_42=https://kovan.infura.io/v3/xxx
JSON_RPC_PROVIDER_10=https://optimism-mainnet.infura.io/v3/xxx
JSON_RPC_PROVIDER_69=https://optimism-kovan.infura.io/v3/xxx
JSON_RPC_PROVIDER_42161=https://arbitrum-mainnet.infura.io/v3/xxx
JSON_RPC_PROVIDER_421611=https://arbitrum-rinkeby.infura.io/v3/xxx
JSON_RPC_PROVIDER_80001=https://polygon-mumbai.infura.io/v3/xxx
JSON_RPC_PROVIDER_421613=https://arbitrum-rinkeby.infura.io/v3/xxx
JSON_RPC_PROVIDER_11155111=https://polygon-mumbai.infura.io/v3/xxx
JSON_RPC_PROVIDER_42220=https://optimism-mainnet.infura.io/v3/xxx
JSON_RPC_PROVIDER_44787=https://optimism-kovan.infura.io/v3/xxx
JSON_RPC_PROVIDER_43114=https://arbitrum-mainnet.infura.io/v3/xxx
JSON_RPC_PROVIDER_8453=https://kovan.infura.io/v3/xxx
JSON_RPC_PROVIDER_56=​https://bsc-dataseed4.binance.org/​
JSON_RPC_PROVIDER_137=https://polygon-mainnet.g.alchemy.com/v2/xxx
UNI_RPC_PROVIDER_CONFIG='{}'
UNICORN_SECRET=''
```
xxx is the infuraId or alchemyId

Or are there any public routing URL services for the uniswap widget?

**Comment by Manish-speqto** [comment]
i am also getting same error

`{
    "name": "RoutingLambda",
    
    "pid": 12,
    "level": 30,
    "err": {
        "message": "indexing_error: {\"response\":{\"errors\":[{\"message\":\"indexing_error\"}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n      query getPools($pageSize: Int!, $id: String) {\\n        pools(\\n          first: $pageSize\\n          \\n          where: { id_gt: $id }\\n        ) {\\n          id\\n          token0 {\\n            symbol\\n            id\\n          }\\n          token1 {\\n            symbol\\n            id\\n          }\\n          feeTier\\n          liquidity\\n          totalValueLockedUSD\\n          totalValueLockedETH\\n        }\\n      }\\n    \",\"variables\":{\"pageSize\":1000,\"id\":\"\"}}}",
        "name": "Error",
        "stack": "Error: indexing_error: {\"response\":{\"errors\":[{\"message\":\"indexing_error\"}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n      query getPools($pageSize: Int!, $id: String) {\\n        pools(\\n          first: $pageSize\\n          \\n          where: { id_gt: $id }\\n        ) {\\n          id\\n          token0 {\\n            symbol\\n            id\\n          }\\n          token1 {\\n            symbol\\n            id\\n          }\\n          feeTier\\n          liquidity\\n          totalValueLockedUSD\\n          totalValueLockedETH\\n        }\\n      }\\n    \",\"variables\":{\"pageSize\":1000,\"id\":\"\"}}}\n    at /var/task/index.js:80:13966\n    at l (/var/task/index.js:80:9141)\n    at Object.next (/var/task/index.js:80:8445)\n    at p (/var/task/index.js:80:8003)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    "msg": "Failed to get pools from subgraph. Retry attempt: 1",
    "time": "2024-02-23T11:40:25.816Z",
    "v": 0
}`
