### ISSUE TITLE
cdk deploy RoutingAPIStack error

### ISSUE THREAD

**Issue by xtuyaowu** [Uniswap/routing-api#823]
routing-api git branch:origin/siyujiang/tenderly-node-100_
smart-order-router git tag v3.39.0

sudo cdk deploy RoutingAPIStack

got error:
12:40:24 PM | CREATE_FAILED        | AWS::Lambda::Permission       | ErrorRate7
777777QU...Permission53E51FA1
Properties validation failed for resource ErrorRate7777777QUIKNODEAlarmPermissi
on53E51FA1 with message:
#/FunctionName: expected maxLength: 140, actual: 142

12:40:27 PM | CREATE_FAILED        | AWS::Lambda::Permission       | ErrorRate1
QUICKNOD...Permission4D593D6C
Properties validation failed for resource ErrorRate1QUICKNODERETHAlarmPermissio
n4D593D6C with message:
#/FunctionName: expected maxLength: 140, actual: 141

12:40:28 PM | CREATE_FAILED        | AWS::Lambda::Permission       | ErrorRate1
1155111A...Permission22BA77BF
Properties validation failed for resource ErrorRate11155111ALCHEMYAlarmPermissi
on22BA77BF with message:
#/FunctionName: expected maxLength: 140, actual: 142

12:40:54 PM | CREATE_FAILED        | AWS::CloudFormation::Stack    | RpcGateway
Fallback...ckResource054D32C9
Embedded stack arn:aws:cloudformation:ap-northeast-1:661085289786:stack/Routing
APIStack-RpcGatewayFallbackStackNestedStackRpcGatewayFallbackStackNestedStackRe
-1SGNJ145W086I/b613ca20-6603-11ef-b421-0a92638ffb97 was not successfully create

 ❌  RoutingAPIStack failed: Error: The stack named RoutingAPIStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Properties validation failed for resource ErrorRate7777777QUIKNODEAlarmPermission53E51FA1 with message:
#/FunctionName: expected maxLength: 140, actual: 142, Properties validation failed for resource ErrorRate1QUICKNODERETHAlarmPermission4D593D6C with message:
#/FunctionName: expected maxLength: 140, actual: 141, Properties validation failed for resource ErrorRate11155111ALCHEMYAlarmPermission22BA77BF with message:
#/FunctionName: expected maxLength: 140, actual: 142, Embedded stack arn:aws:cloudformation:ap-northeast-1:661085289786:stack/RoutingAPIStack-RpcGatewayFallbackStackNestedStackRpcGatewayFallbackStackNestedStackRe-1SGNJ145W086I/b613ca20-6603-11ef-b421-0a92638ffb97 was not successfully created: The following resource(s) failed to create: [ErrorRate11155111ALCHEMYAlarmPermission22BA77BF, ErrorRate1QUICKNODERETHAlarmPermission4D593D6C, ErrorRate7777777QUIKNODEAlarmPermission53E51FA1]. 
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:447:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:450:200276)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:450:181698

 ❌ Deployment failed: Error: The stack named RoutingAPIStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Properties validation failed for resource ErrorRate7777777QUIKNODEAlarmPermission53E51FA1 with message:
#/FunctionName: expected maxLength: 140, actual: 142, Properties validation failed for resource ErrorRate1QUICKNODERETHAlarmPermission4D593D6C with message:
#/FunctionName: expected maxLength: 140, actual: 141, Properties validation failed for resource ErrorRate11155111ALCHEMYAlarmPermission22BA77BF with message:
#/FunctionName: expected maxLength: 140, actual: 142, Embedded stack arn:aws:cloudformation:ap-northeast-1:661085289786:stack/RoutingAPIStack-RpcGatewayFallbackStackNestedStackRpcGatewayFallbackStackNestedStackRe-1SGNJ145W086I/b613ca20-6603-11ef-b421-0a92638ffb97 was not successfully created: The following resource(s) failed to create: [ErrorRate11155111ALCHEMYAlarmPermission22BA77BF, ErrorRate1QUICKNODERETHAlarmPermission4D593D6C, ErrorRate7777777QUIKNODEAlarmPermission53E51FA1]. 
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:447:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:450:200276)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:450:181698

The stack named RoutingAPIStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Properties validation failed for resource ErrorRate7777777QUIKNODEAlarmPermission53E51FA1 with message:
#/FunctionName: expected maxLength: 140, actual: 142, Properties validation failed for resource ErrorRate1QUICKNODERETHAlarmPermission4D593D6C with message:
#/FunctionName: expected maxLength: 140, actual: 141, Properties validation failed for resource ErrorRate11155111ALCHEMYAlarmPermission22BA77BF with message:
#/FunctionName: expected maxLength: 140, actual: 142, Embedded stack arn:aws:cloudformation:ap-northeast-1:661085289786:stack/RoutingAPIStack-RpcGatewayFallbackStackNestedStackRpcGatewayFallbackStackNestedStackRe-1SGNJ145W086I/b613ca20-6603-11ef-b421-0a92638ffb97 was not successfully created: The following resource(s) failed to create: [ErrorRate11155111ALCHEMYAlarmPermission22BA77BF, ErrorRate1QUICKNODERETHAlarmPermission4D593D6C, ErrorRate7777777QUIKNODEAlarmPermission53E51FA1]. 

thanks!

**Comment by xtuyaowu** [comment]
change region
